# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Unit tests"
  lane :unit_tests do
  run_tests(scheme: "SeatAndOrder")
  
  xcov(workspace: "SeatAndOrder.xcworkspace",
  		scheme: "SeatAndOrder",
  		output_directory: "xcov_output")

  danger(danger_id: "unit-tests",
  		dangerfile: "fastlane/DangerFile",
  		github_api_token: ENV["a546ed4ddfdfae79c7151b3a771753f9fbfa7e82"],
  		verbose: true)  
  end
end
