# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Unit tests"
  lane :unit_tests do
    begin
      scan(
        scheme:"SeatAndOrder",
        workspace:"SeatAndOrder.xcworkspace",
        code_coverage:true,
        clean:true,
        output_directory:"fastlane/test_output"
      )
      slather
      codecov_sh = "curl -s https://codecov.io/bash -t 3cf6b7b1-5413-4a3b-838a-41cfa25ba870 -f fastlane/slather_output -X coveragepy -X gcov -X xcode || 'Rompimo todo'"
      sh codecov_sh
    end
  end
end
